### ISSUE TITLE
Wrong output generated for custom datafile

### ISSUE THREAD

**Issue by altineller** [michal34512/Magnetometer-calibration#1]
Hello,

I have been testing many different calibration algoritms mostly cpp, c, and python, and this one is quite nicely written.

I made some changes to read a custom magnetometer datafile as such:

`
mag_generated_data_t read_mag_data() {

    mag_generated_data_t res;

    FILE *file = fopen("magf.txt", "r");
    if(file == NULL) {
        printf("error opening file!\n");
        exit(0);
    }

    int line_count = 0;
    char ch;
    while((ch = fgetc(file)) != EOF) {
        if (ch == '\n') {
            line_count++;
        }
    }

    res.vx = vec_new(line_count);
    res.vy = vec_new(line_count);
    res.vz = vec_new(line_count);

    float x, y, z;
    char line[128];
    int i;
    
    rewind(file);

    while(fgets(line, sizeof(line), file) != NULL) {
        if(sscanf(line, "%f,%f,%f", &x, &y, &z) == 3) {
	        VEC_ELEM(res.vx, i) = x;
            VEC_ELEM(res.vy, i) = y;
            VEC_ELEM(res.vz, i) = z;
            i++;
        } else {
            printf("Error parsing line: %s\n", line);
            exit(0);
        }
    }
    fclose(file);
    return res;
}
`

But when I compare results with other softwares, namely MotionCal and also https://github.com/FHoevi/EllipsoidFit 
it generates wrong soft iron calibration matrix.

Here is the datafile:

[magf.txt](https://github.com/user-attachments/files/17560832/magf.txt)

Here are the results:

data line count: 1730
Calculating calibration data of data points was SUCCESFUL
calibration offset:
[10.3620985004, 11.1872766157, 5.0033984080, ]
calibration transform:
Size (3, 3):
0.025240, 0.000012, 0.000071, 
0.000012, 0.024910, -0.000140, 
0.000071, -0.000140, 0.025779,

Here are results from EllipsoidFit:
center:
 [[10.35599713]
 [11.19132794]
 [ 4.96368039]]
transformation:
 [[ 0.99981783  0.0013117  -0.0025344 ]
 [ 0.0013117   0.98805337 -0.00576219]
 [-0.0025344  -0.00576219  1.01231724]]

As you can see the offsets are almost the same with less than .01 difference, except for z, which is .04 difference. 
These can be related to outlier rejection.

However I have no idea about what is causing the transformation to be calculated differently? 

Any ideas, recomendations or help greatly appreciated.

Best Regards,
C.

**Comment by michal34512** [comment]
Hmm, seems like some problem with scale. Thanks for letting me know, i'll look into that ;)

**Comment by michal34512** [comment]
The difference between my code and `EllipsoidFit` is that my code additionally normalizes the vectors. So, after calling calib_calibrate_point(), the vector’s length is close to 1 (This could be useful when working with a different type of sensor, such as an accelerometer)
EllipsoidFit, on the oher hand does not normalize vectors, so in your case you’ll get vectors with a length of around 40.

For magnetometers, the vector length usually isn’t important, as you typically only care about the direction. However, if you want the results to match `EllipsoidFit`, you can modify `calib_calibrate_rotation` in `sensor_calibration.c` as follows:

Before:
```cpp
    Matrix gain_Rotation = mat_multiply(gain, rotation);
    Matrix res = mat_multiply(eig.eigenvectors, gain_Rotation);
    eig_free(eig);
    mat_free(gain_Rotation);
```
After:
```cpp
    // Matrix gain_Rotation = mat_multiply(gain, rotation);
    Matrix res = mat_multiply(eig.eigenvectors, rotation);
    eig_free(eig);
    // mat_free(gain_Rotation);
```
This way you'll skip the vector normalization step ;)

**Comment by altineller** [comment]
I was revisiting the subject "why my magnetometer is not working" :) and I noticed that even I made these changes in the code, it produced the wrong results. Further more I accidentally discovered that with each run, it will generate a different result for the same input data. Here is example output:

data line count: 37431
Calculating calibration data of data points was SUCCESFUL
calibration offset:
[-5.4978344913, -22.3020683000, -12.5669400928, ]
calibration transform:
Size (3, 3):
1.000000, 0.000001, -0.000001, 
0.000001, 1.000000, 0.000004, 
-0.000001, 0.000004, 1.000000, 

data line count: 37431
Calculating calibration data of data points was SUCCESFUL
calibration offset:
[-5.4978345068, -22.3020684435, -12.5669401432, ]
calibration transform:
Size (3, 3):
1.000000, 0.000000, -0.000000, 
0.000000, 1.000000, 0.000002, 
-0.000000, 0.000002, 1.000000, 

data line count: 37431
Calculating calibration data of data points was SUCCESFUL
calibration offset:
[-5.4978344038, -22.3020679509, -12.5669400127, ]
calibration transform:
Size (3, 3):
1.000000, 0.000001, -0.000001, 
0.000001, 1.000000, 0.000003, 
-0.000001, 0.000003, 1.000000, 

Why could this be happening?

Best Regards,
Can

**Comment by michal34512** [comment]
Hi! Sorry for late response.
Finding best fitting ellipsoid require finding eigenvectors for every eigenvalue of matrix. Finding next eivenvector based on previous one require solving equasion:
$`(A - λI)x = 0`$
which is problematic, because the matrix is singular when λ is an exact eigenvalue.
To overcome this, a small offset is added to λ. This makes the matrix invertible, allowing the equation to be solved iteratively. The small offset is added in this line (file "eigen.c"):
```C
 double lambda = eigVal + ((double) rand() / (double) RAND_MAX) * 0.000001;
```
Since a random number is used here, the result might be slightly different each time you run the program.
But the difference is so small it doesn't really matter in practice.

If you want to get the same result every time, just do something like this:
```C
 double lambda = eigVal + 0.000001;
```
but i'm not sure how this will affect the performance.
